## Решение СЛАУ

### Задание начальных условий:

In [1]:
import numpy as np

In [2]:
n = int(input("Количество неизвестных: "))

Количество неизвестных: 4


In [3]:
A = np.random.randint(-10, 10, size=(n, n))
B = np.random.randint(-10, 10, size=(n, 1))
print(A)
print(B)

[[-10  -2  -5   2]
 [ -2   6   4  -9]
 [  7  -3  -7  -1]
 [ -2   4   0  -3]]
[[-8]
 [-4]
 [-9]
 [ 1]]


### Матричный метод:

In [4]:
ans = np.linalg.inv(A).dot(B)
print(ans.reshape(1, n))

[[0.46909871 1.91888412 0.65922747 1.91244635]]


### Метод Крамера:

In [5]:
ans = np.array([])
A_det = np.linalg.det(A)
for i in range(n):
    A_cp = A.copy()
    A_cp[::, i] = B.reshape(1, n)
    det_x = np.linalg.det(A_cp)
    x = det_x / A_det
    ans = np.append(ans, x)
print(ans)

[0.46909871 1.91888412 0.65922747 1.91244635]
