### Примеры со своими значениями:

In [1]:
import numpy as np

#### Вектор:

##### Вектор-строка:

In [2]:
v_hor_np = np.array([2, 3])
print(v_hor_np )

[2 3]


In [3]:
v_hor_zeros_v1 = np.zeros((6,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0. 0.]


In [4]:
v_hor_zeros_v2 = np.zeros((1, 6))
print(v_hor_zeros_v2 )

[[0. 0. 0. 0. 0. 0.]]


In [5]:
v_hor_one_v1 = np.ones((6,))
print(v_hor_one_v1)
v_hor_one_v2 = np.ones((1, 6))
print(v_hor_one_v2)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]]


##### Вектор-столбец:

In [6]:
v_vert_np = np.array([[3], [4]])
print(v_vert_np)

[[3]
 [4]]


In [7]:
v_vert_zeros = np.zeros((6, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [8]:
v_vert_ones = np.ones((6, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


#### Квадратная матрица:

In [9]:
m_sqr_arr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(m_sqr_arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
m_sqr = [[2, 3, 4], [5, 6, 7], [8, 9, 10]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
m_sqr_mx = np.matrix([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(m_sqr_mx)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
m_sqr_mx = np.matrix('2 3 4; 5 6 7; 8 9 10')
print(m_sqr_mx)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


##### Диагональная матрица:

In [13]:
m_diag = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [14]:
m_sqr_mx = np.matrix('2 3 4; 5 6 7; 8 9 10')

In [15]:
diag = np.diag(m_sqr_mx)
print(diag)

[ 2  6 10]


In [16]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[ 2  0  0]
 [ 0  6  0]
 [ 0  0 10]]


##### Единичная матрица:

In [17]:
m_e = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
m_idnt = np.identity(4)
print(m_idnt)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##### Нулевая матрица:

In [20]:
m_zeros = np.zeros((4, 4))
print(m_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### Задание матрицы в общем виде:

In [21]:
m_mx = np.matrix('2 3 4; 5 6 7')
print(m_mx)

[[2 3 4]
 [5 6 7]]


In [22]:
m_var = np.zeros((3, 4))
print(m_var)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### Транспонирование матрицы:

In [23]:
A = np.matrix('2 3 4; 5 6 7')
print(A)

[[2 3 4]
 [5 6 7]]


In [24]:
A_t = A.transpose()
print(A_t)

[[2 5]
 [3 6]
 [4 7]]


In [25]:
print(A.T)

[[2 5]
 [3 6]
 [4 7]]


In [26]:
A = np.matrix('2 3 4; 5 6 7')
print(A)
R = (A.T).T
print(R)

[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]


In [27]:
A = np.matrix('2 3 4; 5 6 7')
B = np.matrix('4 5 6; 7 8 9')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[ 6 12]
 [ 8 14]
 [10 16]]
[[ 6 12]
 [ 8 14]
 [10 16]]


In [28]:
A = np.matrix('2 3; 5 6')
B = np.matrix('4 5; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[29 62]
 [34 73]]
[[29 62]
 [34 73]]


In [29]:
A = np.matrix('4 5 6; 7 8 9')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[12 21]
 [15 24]
 [18 27]]
[[12 21]
 [15 24]
 [18 27]]


In [30]:
A = np.matrix('2 3; 5 6')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

-3
-3


#### Действия над матрицами:

##### Умножение матрицы на число:

In [31]:
A = np.matrix('4 5 6; 7 8 9')
C = 3 * A
print(C)

[[12 15 18]
 [21 24 27]]


In [32]:
A = np.matrix('2 3; 5 6')
L = 1 * A
R = A
print(L)
print(R)

[[2 3]
 [5 6]]
[[2 3]
 [5 6]]


In [33]:
A = np.matrix('2 3; 5 6')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [34]:
A = np.matrix('2 3; 5 6')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[10 15]
 [25 30]]
[[10 15]
 [25 30]]


In [35]:
A = np.matrix('2 3; 5 6')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[12 18]
 [30 36]]
[[12 18]
 [30 36]]


In [36]:
A = np.matrix('2 3; 5 6')
B = np.matrix('4 5; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [36 42]]
[[18 24]
 [36 42]]


##### Сложение матриц:

In [37]:
A = np.matrix('4 5 6; 7 8 9')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[12  6 11]
 [13 17 21]]


In [38]:
A = np.matrix('2 3; 5 6')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)
print(R)

[[ 7  9]
 [12 14]]
[[ 7  9]
 [12 14]]


In [39]:
A = np.matrix('2 3; 5 6')
B = np.matrix('5 6; 7 8')
C = np.matrix('7 8; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[14 17]
 [21 17]]
[[14 17]
 [21 17]]


In [40]:
A = np.matrix('5 6; 7 8')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


##### Умножение матриц:

In [41]:
A = np.matrix('1 2; 4 5')
B = np.matrix('7; 9')
C = A.dot(B)
print(C)

[[25]
 [73]]


In [42]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [43]:
A = np.matrix('2 3; 5 6')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[ 56  68]
 [119 146]]
[[ 56  68]
 [119 146]]


In [44]:
A = np.matrix('2 3; 5 6')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)
print(R)

[[31 36]
 [67 78]]
[[40 51]
 [54 69]]


In [45]:
A = np.matrix('2 3; 5 6')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)
print(A)

[[2 3]
 [5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]


In [46]:
A = np.matrix('2 3; 5 6')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


#### Определитель матрицы:

In [47]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]


In [48]:
np.linalg.det(A)

-36.0

In [49]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]
[[-4  1  4]
 [-1  4  3]
 [ 1 -1  1]]
-36.0
-36.0


In [50]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]


-36.0

In [51]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)
B = np.matrix('10 3 -1; -4 -1 2; 2 3 1')
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]
[[10  3 -1]
 [-4 -1  2]
 [ 2  3  1]]


-36.0

In [52]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]


-36.0

In [53]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k
det_B

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]
[[-4 -1  1]
 [ 1  4 -1]
 [ 8  6  2]]


-72.0

In [54]:
A = np.matrix('-5 -1 2; -3 -1 2; 8 3 1')
B = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
round(np.linalg.det(C), 3)
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

[[-5 -1  2]
 [-2  3  1]
 [ 8  3  1]]
[[-5 -1  2]
 [-3 -1  2]
 [ 8  3  1]]
[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]


-22.0

In [55]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]
[[-4 -1  1]
 [-7  2  1]
 [ 4  3  1]]


-36.0

In [56]:
A = np.matrix('-4 -1 1; 1 4 -1; 4 3 1')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

[[-4 -1  1]
 [ 1  4 -1]
 [ 4  3  1]]


0.0

In [57]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


0.0

#### Обратная матрица:

In [58]:
A = np.matrix('1 -3 4; 2 5 2; 2 -1 2')
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.33333333 -0.05555556  0.72222222]
 [-0.          0.16666667 -0.16666667]
 [ 0.33333333  0.13888889 -0.30555556]]


In [59]:
A = np.matrix('1 -3 4; 2 5 2; 2 -1 2')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1 -3  4]
 [ 2  5  2]
 [ 2 -1  2]]
[[ 1. -3.  4.]
 [ 2.  5.  2.]
 [ 2. -1.  2.]]


In [60]:
A = np.matrix('1 -3 4; 2 5 2; 2 -1 2')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[-3.33333333e-01  1.38777878e-17  3.33333333e-01]
 [-5.55555556e-02  1.66666667e-01  1.38888889e-01]
 [ 7.22222222e-01 -1.66666667e-01 -3.05555556e-01]]
[[-0.33333333 -0.          0.33333333]
 [-0.05555556  0.16666667  0.13888889]
 [ 0.72222222 -0.16666667 -0.30555556]]


In [61]:
A = np.matrix('1 -3 4; 2 5 2; 2 -1 2')
B = np.matrix('1 -2 4; 3 1 -5; 9 -1 2')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.05882353  0.01960784 -0.07843137]
 [ 0.44444444 -0.00925926 -0.71296296]
 [ 0.12418301 -0.02342048 -0.15631808]]
[[ 0.05882353  0.01960784 -0.07843137]
 [ 0.44444444 -0.00925926 -0.71296296]
 [ 0.12418301 -0.02342048 -0.15631808]]


#### Ранг матрицы:

In [62]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

3


In [64]:
m_eye[2][2] = 0
print(m_eye)
rank = np.linalg.matrix_rank(m_eye)
print(rank)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
2
